# Generated by Django 3.0.6 on 2020-05-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speciality',
            new_name='Specialty',
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(default='', max_length=128),
        ),
    ]
